// File: SeatbeltReminder_SWC.c

#include "SeatbeltReminder_SWC.h"
#include "Rte_SeatbeltReminder_SWC.h" // Assumed to be generated by an RTE tool

// Definition of the runnable entity function
void RE_MainFunction_100ms(void)
{
    // 1. Declare local variables to hold the port data
    uint16 vehicle_speed;
    boolean is_seatbelt_fastened;
    Std_ReturnType status_speed;
    Std_ReturnType status_seatbelt;

    // 2. Read data from the input ports using the RTE API
    status_speed = Rte_Read_R_VehicleSpeed_VehicleSpeed_Kph(&vehicle_speed);
    status_seatbelt = Rte_Read_R_SeatbeltStatus_IsSeatbeltFastened(&is_seatbelt_fastened);

    // 3. Implement the core logic
    if ((status_speed == RTE_E_OK) && (status_seatbelt == RTE_E_OK))
    {
        if ((vehicle_speed > 5) && (is_seatbelt_fastened == FALSE))
        {
            // 4. Write the result to the output port
            (void)Rte_Write_P_WarningLight_IsWarningLightActive(TRUE);
        }
        else
        {
            // 4. Write the result to the output port
            (void)Rte_Write_P_WarningLight_IsWarningLightActive(FALSE);
        }
    }
}