name: CMake CI for AUTOSAR SWC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v3

    # Step 2: Configure the project using CMake
    # Creates the build directory and generates the build system
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    # Step 3: Build the project using the generated build system
    - name: Build Project
      run: cmake --build ${{github.workspace}}/build

    # Step 4: Run the executable to verify it works
    # The executable is now located inside the 'build' directory
    - name: Run Test Application
      run: ${{github.workspace}}/build/autosar_test